# Expanded sample books data with extended details (40 books)
# Using Open Library cover URLs pattern: https://covers.openlibrary.org/b/isbn/{ISBN}-L.jpg
BOOKS = [
    {
        'book_id': 1,
        'title': 'Pride and Prejudice',
        'author': 'Jane Austen',
        'isbn': '9780141439518',
        'genre': 'Classic Literature',
        'description': 'A witty exploration of manners, upbringing, morality and marriage in early 19th-century England through the lives of the Bennet family.',
        'publication_year': 1813,
        'publisher': 'Penguin Classics',
        'page_count': 432,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg'
    },
    {
        'book_id': 2,
        'title': '1984',
        'author': 'George Orwell',
        'isbn': '9780451524935',
        'genre': 'Dystopian Fiction',
        'description': 'A chilling depiction of perpetual war, government surveillance, and public manipulation under a totalitarian regime.',
        'publication_year': 1949,
        'publisher': 'Signet Classic',
        'page_count': 328,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg'
    },
    {
        'book_id': 3,
        'title': 'To Kill a Mockingbird',
        'author': 'Harper Lee',
        'isbn': '9780446310789',
        'genre': 'Literary Fiction',
        'description': 'A moving story of racial injustice and childhood moral growth in the American South.',
        'publication_year': 1960,
        'publisher': 'Grand Central Publishing',
        'page_count': 324,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780446310789-L.jpg'
    },
    {
        'book_id': 4,
        'title': 'The Great Gatsby',
        'author': 'F. Scott Fitzgerald',
        'isbn': '9780743273565',
        'genre': 'Classic Literature',
        'description': 'A portrait of the Jazz Age that explores themes of decadence, idealism and social upheaval.',
        'publication_year': 1925,
        'publisher': 'Scribner',
        'page_count': 180,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg'
    },
    {
        'book_id': 5,
        'title': 'One Hundred Years of Solitude',
        'author': 'Gabriel García Márquez',
        'isbn': '9780060883287',
        'genre': 'Magical Realism',
        'description': 'The multi-generational story of the Buendía family in the fictional town of Macondo.',
        'publication_year': 1967,
        'publisher': 'Harper Perennial',
        'page_count': 417,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg'
    },
    {
        'book_id': 6,
        'title': 'The Catcher in the Rye',
        'author': 'J.D. Salinger',
        'isbn': '9780316769488',
        'genre': 'Literary Fiction',
        'description': 'A teenager named Holden Caulfield recounts days in New York City after being expelled from prep school.',
        'publication_year': 1951,
        'publisher': 'Little, Brown and Company',
        'page_count': 214,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg'
    },
    {
        'book_id': 7,
        'title': 'Brave New World',
        'author': 'Aldous Huxley',
        'isbn': '9780060850524',
        'genre': 'Dystopian Fiction',
        'description': 'A visionary novel about a scientifically advanced and socially controlled future society.',
        'publication_year': 1932,
        'publisher': 'Harper Perennial Modern Classics',
        'page_count': 268,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg'
    },
    {
        'book_id': 8,
        'title': 'Moby-Dick',
        'author': 'Herman Melville',
        'isbn': '9780142437247',
        'genre': 'Adventure',
        'description': 'Captain Ahab hunts the white whale Moby Dick, an epic tale of obsession and revenge.',
        'publication_year': 1851,
        'publisher': 'Penguin Classics',
        'page_count': 720,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg'
    },
    {
        'book_id': 9,
        'title': 'The Hobbit',
        'author': 'J.R.R. Tolkien',
        'isbn': '9780345339683',
        'genre': 'Fantasy',
        'description': 'Bilbo Baggins embarks on a journey with dwarves to reclaim a treasure guarded by Smaug the dragon.',
        'publication_year': 1937,
        'publisher': 'Del Rey',
        'page_count': 300,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780345339683-L.jpg'
    },
    {
        'book_id': 10,
        'title': 'Harry Potter and the Sorcerer\'s Stone',
        'author': 'J.K. Rowling',
        'isbn': '9780590353427',
        'genre': 'Fantasy',
        'description': 'A young boy discovers he is a wizard and attends Hogwarts School of Witchcraft and Wizardry.',
        'publication_year': 1997,
        'publisher': 'Scholastic',
        'page_count': 309,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780590353427-L.jpg'
    },
    {
        'book_id': 11,
        'title': 'The Road',
        'author': 'Cormac McCarthy',
        'isbn': '9780307387899',
        'genre': 'Post-Apocalyptic',
        'description': 'A bleak, moving tale of a father and son traveling through a ravaged landscape after an unspecified cataclysm.',
        'publication_year': 2006,
        'publisher': 'Vintage',
        'page_count': 287,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780307387899-L.jpg'
    },
    {
        'book_id': 12,
        'title': 'The Alchemist',
        'author': 'Paulo Coelho',
        'isbn': '9780061122415',
        'genre': 'Philosophical Fiction',
        'description': 'A shepherd boy named Santiago seeks his destiny and learns about listening to his heart and following dreams.',
        'publication_year': 1988,
        'publisher': 'HarperOne',
        'page_count': 208,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg'
    },
    {
        'book_id': 13,
        'title': 'Beloved',
        'author': 'Toni Morrison',
        'isbn': '9780307277671',
        'genre': 'Historical Fiction',
        'description': 'A powerful novel about the trauma of slavery and its lingering effects on a family.',
        'publication_year': 1987,
        'publisher': 'Vintage',
        'page_count': 324,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780307277671-L.jpg'
    },
    {
        'book_id': 14,
        'title': 'The Name of the Wind',
        'author': 'Patrick Rothfuss',
        'isbn': '9780756404741',
        'genre': 'Fantasy',
        'description': 'A gifted young man grows to be the most notorious magician his world has ever seen.',
        'publication_year': 2007,
        'publisher': 'DAW Books',
        'page_count': 662,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg'
    },
    {
        'book_id': 15,
        'title': 'Sapiens: A Brief History of Humankind',
        'author': 'Yuval Noah Harari',
        'isbn': '9780062316097',
        'genre': 'Non-fiction',
        'description': 'A broad history of humankind from the Stone Age through the 21st century, exploring how biology and history have defined us.',
        'publication_year': 2011,
        'publisher': 'Harper',
        'page_count': 443,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg'
    },
    {
        'book_id': 16,
        'title': 'Dune',
        'author': 'Frank Herbert',
        'isbn': '9780441172719',
        'genre': 'Science Fiction',
        'description': 'A complex tale of politics, religion, and ecology on the desert planet Arrakis.',
        'publication_year': 1965,
        'publisher': 'Ace',
        'page_count': 896,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg'
    },
    {
        'book_id': 17,
        'title': 'The Silent Patient',
        'author': 'Alex Michaelides',
        'isbn': '9781250301697',
        'genre': 'Psychological Thriller',
        'description': 'A woman shoots her husband and then never speaks another word.',
        'publication_year': 2019,
        'publisher': 'Celadon Books',
        'page_count': 325,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg'
    },
    {
        'book_id': 18,
        'title': 'The Seven Husbands of Evelyn Hugo',
        'author': 'Taylor Jenkins Reid',
        'isbn': '9781501161933',
        'genre': 'Historical Fiction',
        'description': 'An aging Hollywood starlet reveals her life story to an unknown journalist.',
        'publication_year': 2017,
        'publisher': 'Washington Square Press',
        'page_count': 400,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781501161933-L.jpg'
    },
    {
        'book_id': 19,
        'title': 'Project Hail Mary',
        'author': 'Andy Weir',
        'isbn': '9780593135204',
        'genre': 'Science Fiction',
        'description': 'An astronaut wakes up alone on a spacecraft with no memory of how he got there.',
        'publication_year': 2021,
        'publisher': 'Ballantine Books',
        'page_count': 496,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg'
    },
    {
        'book_id': 20,
        'title': 'Where the Crawdads Sing',
        'author': 'Delia Owens',
        'isbn': '9780735219090',
        'genre': 'Literary Fiction',
        'description': 'A coming-of-age story about a young girl raised in the marshlands of North Carolina.',
        'publication_year': 2018,
        'publisher': 'G.P. Putnam\'s Sons',
        'page_count': 384,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780735219090-L.jpg'
    },
    {
        'book_id': 21,
        'title': 'The Hitchhiker\'s Guide to the Galaxy',
        'author': 'Douglas Adams',
        'isbn': '9780345391803',
        'genre': 'Science Fiction',
        'description': 'The misadventures of Arthur Dent as he travels through space after Earth\'s destruction.',
        'publication_year': 1979,
        'publisher': 'Del Rey',
        'page_count': 224,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg'
    },
    {
        'book_id': 22,
        'title': 'The Midnight Library',
        'author': 'Matt Haig',
        'isbn': '9780525559474',
        'genre': 'Contemporary Fiction',
        'description': 'A library between life and death offers infinite possibilities to change one\'s life story.',
        'publication_year': 2020,
        'publisher': 'Viking',
        'page_count': 304,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg'
    },
    {
        'book_id': 23,
        'title': 'The Thursday Murder Club',
        'author': 'Richard Osman',
        'isbn': '9780241425442',
        'genre': 'Mystery',
        'description': 'Four retirees meet weekly to solve cold cases, until a live murder occurs nearby.',
        'publication_year': 2020,
        'publisher': 'Viking',
        'page_count': 382,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780241425442-L.jpg'
    },
    {
        'book_id': 24,
        'title': 'The Song of Achilles',
        'author': 'Madeline Miller',
        'isbn': '9780062060624',
        'genre': 'Historical Fiction',
        'description': 'A retelling of the Iliad from Patroclus\'s perspective, focusing on his relationship with Achilles.',
        'publication_year': 2011,
        'publisher': 'Ecco',
        'page_count': 416,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780062060624-L.jpg'
    },
    {
        'book_id': 25,
        'title': 'Mexican Gothic',
        'author': 'Silvia Moreno-Garcia',
        'isbn': '9780525620785',
        'genre': 'Horror',
        'description': 'A young woman investigates her cousin\'s claims of supernatural horrors at a remote mansion.',
        'publication_year': 2020,
        'publisher': 'Del Rey',
        'page_count': 320,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780525620785-L.jpg'
    },
    {
        'book_id': 26,
        'title': 'Klara and the Sun',
        'author': 'Kazuo Ishiguro',
        'isbn': '9780571364879',
        'genre': 'Literary Fiction',
        'description': 'An Artificial Friend observes the world and contemplates the meaning of love and connection.',
        'publication_year': 2021,
        'publisher': 'Faber & Faber',
        'page_count': 320,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780571364879-L.jpg'
    },
    {
        'book_id': 27,
        'title': 'The House in the Cerulean Sea',
        'author': 'TJ Klune',
        'isbn': '9781250217288',
        'genre': 'Fantasy',
        'description': 'A case worker is sent to evaluate six dangerous magical children at a remote orphanage.',
        'publication_year': 2020,
        'publisher': 'Tor Books',
        'page_count': 396,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781250217288-L.jpg'
    },
    {
        'book_id': 28,
        'title': 'A Court of Thorns and Roses',
        'author': 'Sarah J. Maas',
        'isbn': '9781619634442',
        'genre': 'Fantasy',
        'description': 'A huntress enters a magical realm as punishment for killing a faerie.',
        'publication_year': 2015,
        'publisher': 'Bloomsbury',
        'page_count': 419,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781619634442-L.jpg'
    },
    {
        'book_id': 29,
        'title': 'The Invisible Life of Addie LaRue',
        'author': 'V.E. Schwab',
        'isbn': '9780765387561',
        'genre': 'Fantasy',
        'description': 'A woman makes a Faustian bargain to live forever but is cursed to be forgotten by everyone she meets.',
        'publication_year': 2020,
        'publisher': 'Tor Books',
        'page_count': 448,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780765387561-L.jpg'
    },
    {
        'book_id': 30,
        'title': 'The Psychology of Money',
        'author': 'Morgan Housel',
        'isbn': '9780857197689',
        'genre': 'Non-fiction',
        'description': 'Explores the strange ways people think about money and teaches how to make better financial decisions.',
        'publication_year': 2020,
        'publisher': 'Harriman House',
        'page_count': 256,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg'
    },
    {
        'book_id': 31,
        'title': 'Atomic Habits',
        'author': 'James Clear',
        'isbn': '9780735211292',
        'genre': 'Self-Help',
        'description': 'A guide to building good habits and breaking bad ones using proven scientific methods.',
        'publication_year': 2018,
        'publisher': 'Avery',
        'page_count': 320,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg'
    },
    {
        'book_id': 32,
        'title': 'The Anthropocene Reviewed',
        'author': 'John Green',
        'isbn': '9780525555216',
        'genre': 'Essays',
        'description': 'A collection of personal essays reviewing different facets of the human-centered planet on a five-star scale.',
        'publication_year': 2021,
        'publisher': 'Dutton Books',
        'page_count': 293,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780525555216-L.jpg'
    },
    {
        'book_id': 33,
        'title': 'The Four Winds',
        'author': 'Kristin Hannah',
        'isbn': '9781250178606',
        'genre': 'Historical Fiction',
        'description': 'A woman struggles to keep her family alive during the Dust Bowl era of the 1930s.',
        'publication_year': 2021,
        'publisher': 'St. Martin\'s Press',
        'page_count': 464,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781250178606-L.jpg'
    },
    {
        'book_id': 34,
        'title': 'The Paris Library',
        'author': 'Janet Skeslien Charles',
        'isbn': '9781982134198',
        'genre': 'Historical Fiction',
        'description': 'Based on the true story of the librarians who risked their lives during World War II.',
        'publication_year': 2021,
        'publisher': 'Atria Books',
        'page_count': 368,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781982134198-L.jpg'
    },
    {
        'book_id': 35,
        'title': 'The Vanishing Half',
        'author': 'Brit Bennett',
        'isbn': '9780525536291',
        'genre': 'Literary Fiction',
        'description': 'Twin sisters lead very different lives after running away from their small, southern black community.',
        'publication_year': 2020,
        'publisher': 'Riverhead Books',
        'page_count': 352,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780525536291-L.jpg'
    },
    {
        'book_id': 36,
        'title': 'The Guest List',
        'author': 'Lucy Foley',
        'isbn': '9780062868930',
        'genre': 'Mystery',
        'description': 'A wedding celebration turns deadly on a remote island off the coast of Ireland.',
        'publication_year': 2020,
        'publisher': 'William Morrow',
        'page_count': 320,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780062868930-L.jpg'
    },
    {
        'book_id': 37,
        'title': 'Think Again',
        'author': 'Adam Grant',
        'isbn': '9781984878106',
        'genre': 'Non-fiction',
        'description': 'Explores the power of knowing what you don\'t know and how to rethink and unlearn.',
        'publication_year': 2021,
        'publisher': 'Viking',
        'page_count': 320,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781984878106-L.jpg'
    },
    {
        'book_id': 38,
        'title': 'The Mountains Sing',
        'author': 'Nguyễn Phan Quế Mai',
        'isbn': '9781616208189',
        'genre': 'Historical Fiction',
        'description': 'A Vietnamese family\'s journey through war and peace across generations.',
        'publication_year': 2020,
        'publisher': 'Algonquin Books',
        'page_count': 352,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781616208189-L.jpg'
    },
    {
        'book_id': 39,
        'title': 'A Promised Land',
        'author': 'Barack Obama',
        'isbn': '9781524763169',
        'genre': 'Autobiography',
        'description': 'The first volume of Barack Obama\'s presidential memoirs.',
        'publication_year': 2020,
        'publisher': 'Crown',
        'page_count': 768,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781524763169-L.jpg'
    },
    {
        'book_id': 40,
        'title': 'The Midnight Rose',
        'author': 'Lucinda Riley',
        'isbn': '9781447218432',
        'genre': 'Historical Fiction',
        'description': 'A multi-generational saga spanning from India under British rule to present-day England.',
        'publication_year': 2014,
        'publisher': 'Pan MacMillan',
        'page_count': 496,
        'language': 'English',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781447218432-L.jpg'
    }
]